### ISSUE TITLE
is this production ready?

### ISSUE THREAD

**Issue by sufleR** [bigcommerce/omniauth-bigcommerce#1]
hi, 

I want to create bigcommerce connected application using API.
I have developer account but there is no documentation about omniauth authentication.

Is this gem ready to use with bigcommerce application?
When it will be ready?

Thank you for answers

Edit:
I found some information about integrated apps [here](https://developers.bigcommerceapp.com/docs/apps).
I cannot find any option to create such application on my developer account/dashboard.

**Comment by mattolson** [comment]
Yes, this is production ready. For more information, see https://developer.bigcommerce.com/api/callback and for a reference implementation of a simple app, see https://github.com/bigcommerce/hello-world-app-ruby-sinatra
