### ISSUE TITLE
request.env['omniauth.auth'] is always nil in callback

### ISSUE THREAD

**Issue by bdensmore** [bigcommerce/omniauth-bigcommerce#18]
I've read through the documentation and followed set up from a couple of different sources but I can never seem to get the Auth hash back in the callback url.

I'm using Rails 4.2.10

I have a draft application with the temporary callback url set as:
https://43181125.ngrok.io/auth/bigcommerce/callback

I have config/initializers/omniauth.rb set up as:
```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :bigcommerce, ENV['BC_CLIENT_ID'], ENV['BC_CLIENT_SECRET']
end
```

right now the omniauths_controller.rb just has the callback action
```
  def callback
    @auth = request.env['omniauth.auth']
    render 'bigcommerce/index', status: 200, layout: nil
  end
```

The params being passed into the action from my draft app are as follows:

```
{"code"=>"{some code}",
 "context"=>"{store context}",
 "scope"=>"store_v2_customers_login store_v2_default store_v2_information_read_only",
 "name"=>"bigcommerce"}
```

Am I possibly missing something?

Thank you,
Ben

**Comment by bdensmore** [comment]
As a follow up to this. The app I'm trying to implement this in is using devise and has the omniauth Facebook and Google strategies implemented in the devise.rb file. I'm guessing here, but I think this might be somehow hijacking the 'omniauth.auth' hash.

As as test I created a brand new rails app with nothing in it but the omniauth-bigcommerce gem and set things up the same way I do in my real app and the Auth hash comes back the way I expected.

Is there some other config option I can put in the omniauth initializer that can force the bigcommerce callback to run correctly?

**Comment by bdensmore** [comment]
I was able to resolve this by adding the callback_path property to the omniauth.rb initializer.

So my omniauth.rb file looks like:

```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :bigcommerce, ENV['BC_CLIENT_ID'], ENV['BC_CLIENT_SECRET'], {
    callback_path: '/auth/bigcommerce/callback'
  }
end
```

**Comment by dvjones89** [comment]
I encountered this exact problems in my Ruby on Rails application when using the `google_oauth2` strategy and `splitwise` strategies simultaneously. 

Happily, @bdensmore's tip about setting the `callback_path` fixed the issue, though since I'm using `omniauth` in conjunction with `devise`, I had to edit the `initializers/devise.rb` file, rather than `initializers/omniauth.rb`:

```
config.omniauth :splitwise, ENV['SPLITWISE_CLIENT_ID'], ENV['SPLITWISE_CLIENT_SECRET'], callback_path: "/auth/splitwise/callback"
```
