### ISSUE TITLE
Is this gem still maintained?

### ISSUE THREAD

**Issue by seashellski** [bigcommerce/omniauth-bigcommerce#22]
Hello 👋

Wondering if this is still being maintained - there doesn't appear to be a commit in over a year and the dependencies are getting a little dated.

For example, the `oauth2` gem dependency is locked to a version that is now 2 years out of date...

Happy to throw a PR your way if it will get some consideration!

**Comment by philipmuir** [comment]
It will get some consideration

**Comment by j05h** [comment]
@seashellski we will definitely review a PR if you would like to submit. We're going to prioritize a fix ourselves, but you are welcome to submit a PR if you have one ready.

Note that we'd like to do a bit more formal testing beyond just the units in place to ensure everything works properly on the upgrade, so we'll likely do a `.pre` release before a full `0.3.4` comes out.

Thanks

**Comment by j05h** [comment]
We've pushed out our release for 0.3.3. Should be showing up on RubyGems within the next few minutes:

[v0.3.3](https://github.com/bigcommerce/omniauth-bigcommerce/tree/v0.3.3)

**Comment by ssteffen** [comment]
This has been pushed to [RubyGems](https://rubygems.org/gems/omniauth-bigcommerce/versions/0.3.0). Thanks!

**Comment by seashellski** [comment]
Woo!
